// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/services/reporting.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The core request message for generating a report for a custom date range.
type GenerateComplianceReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	ReportTitle   string                 `protobuf:"bytes,4,opt,name=report_title,json=reportTitle,proto3" json:"report_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateComplianceReportRequest) Reset() {
	*x = GenerateComplianceReportRequest{}
	mi := &file_v1_services_reporting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateComplianceReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateComplianceReportRequest) ProtoMessage() {}

func (x *GenerateComplianceReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_services_reporting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateComplianceReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateComplianceReportRequest) Descriptor() ([]byte, []int) {
	return file_v1_services_reporting_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateComplianceReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GenerateComplianceReportRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GenerateComplianceReportRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GenerateComplianceReportRequest) GetReportTitle() string {
	if x != nil {
		return x.ReportTitle
	}
	return ""
}

// Request for a full calendar year report.
type GenerateAnnualReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAnnualReportRequest) Reset() {
	*x = GenerateAnnualReportRequest{}
	mi := &file_v1_services_reporting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAnnualReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAnnualReportRequest) ProtoMessage() {}

func (x *GenerateAnnualReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_services_reporting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAnnualReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateAnnualReportRequest) Descriptor() ([]byte, []int) {
	return file_v1_services_reporting_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateAnnualReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GenerateAnnualReportRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

// Request for a specific month's report.
type GenerateMonthlyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"` // 1 = January, 12 = December
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateMonthlyReportRequest) Reset() {
	*x = GenerateMonthlyReportRequest{}
	mi := &file_v1_services_reporting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateMonthlyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMonthlyReportRequest) ProtoMessage() {}

func (x *GenerateMonthlyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_services_reporting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMonthlyReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateMonthlyReportRequest) Descriptor() ([]byte, []int) {
	return file_v1_services_reporting_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateMonthlyReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GenerateMonthlyReportRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GenerateMonthlyReportRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

// The standard response for all report generation RPCs.
type GenerateComplianceReportResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReportDownloadUrl string                 `protobuf:"bytes,1,opt,name=report_download_url,json=reportDownloadUrl,proto3" json:"report_download_url,omitempty"`
	ReportId          string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateComplianceReportResponse) Reset() {
	*x = GenerateComplianceReportResponse{}
	mi := &file_v1_services_reporting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateComplianceReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateComplianceReportResponse) ProtoMessage() {}

func (x *GenerateComplianceReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_services_reporting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateComplianceReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateComplianceReportResponse) Descriptor() ([]byte, []int) {
	return file_v1_services_reporting_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateComplianceReportResponse) GetReportDownloadUrl() string {
	if x != nil {
		return x.ReportDownloadUrl
	}
	return ""
}

func (x *GenerateComplianceReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

var File_v1_services_reporting_proto protoreflect.FileDescriptor

const file_v1_services_reporting_proto_rawDesc = "" +
	"\n" +
	"\x1bv1/services/reporting.proto\x12\x0fscg.v1.services\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\x1fGenerateComplianceReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12!\n" +
	"\freport_title\x18\x04 \x01(\tR\vreportTitle\"N\n" +
	"\x1bGenerateAnnualReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"e\n" +
	"\x1cGenerateMonthlyReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"o\n" +
	" GenerateComplianceReportResponse\x12.\n" +
	"\x13report_download_url\x18\x01 \x01(\tR\x11reportDownloadUrl\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId2\x87\x03\n" +
	"\x10ReportingService\x12\x7f\n" +
	"\x18GenerateComplianceReport\x120.scg.v1.services.GenerateComplianceReportRequest\x1a1.scg.v1.services.GenerateComplianceReportResponse\x12w\n" +
	"\x14GenerateAnnualReport\x12,.scg.v1.services.GenerateAnnualReportRequest\x1a1.scg.v1.services.GenerateComplianceReportResponse\x12y\n" +
	"\x15GenerateMonthlyReport\x12-.scg.v1.services.GenerateMonthlyReportRequest\x1a1.scg.v1.services.GenerateComplianceReportResponseBKZIgithub.com/SupplyChainGuard/scg-protos/protoc-gen/go/v1/services;servicesb\x06proto3"

var (
	file_v1_services_reporting_proto_rawDescOnce sync.Once
	file_v1_services_reporting_proto_rawDescData []byte
)

func file_v1_services_reporting_proto_rawDescGZIP() []byte {
	file_v1_services_reporting_proto_rawDescOnce.Do(func() {
		file_v1_services_reporting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_services_reporting_proto_rawDesc), len(file_v1_services_reporting_proto_rawDesc)))
	})
	return file_v1_services_reporting_proto_rawDescData
}

var file_v1_services_reporting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_services_reporting_proto_goTypes = []any{
	(*GenerateComplianceReportRequest)(nil),  // 0: scg.v1.services.GenerateComplianceReportRequest
	(*GenerateAnnualReportRequest)(nil),      // 1: scg.v1.services.GenerateAnnualReportRequest
	(*GenerateMonthlyReportRequest)(nil),     // 2: scg.v1.services.GenerateMonthlyReportRequest
	(*GenerateComplianceReportResponse)(nil), // 3: scg.v1.services.GenerateComplianceReportResponse
	(*timestamppb.Timestamp)(nil),            // 4: google.protobuf.Timestamp
}
var file_v1_services_reporting_proto_depIdxs = []int32{
	4, // 0: scg.v1.services.GenerateComplianceReportRequest.start_date:type_name -> google.protobuf.Timestamp
	4, // 1: scg.v1.services.GenerateComplianceReportRequest.end_date:type_name -> google.protobuf.Timestamp
	0, // 2: scg.v1.services.ReportingService.GenerateComplianceReport:input_type -> scg.v1.services.GenerateComplianceReportRequest
	1, // 3: scg.v1.services.ReportingService.GenerateAnnualReport:input_type -> scg.v1.services.GenerateAnnualReportRequest
	2, // 4: scg.v1.services.ReportingService.GenerateMonthlyReport:input_type -> scg.v1.services.GenerateMonthlyReportRequest
	3, // 5: scg.v1.services.ReportingService.GenerateComplianceReport:output_type -> scg.v1.services.GenerateComplianceReportResponse
	3, // 6: scg.v1.services.ReportingService.GenerateAnnualReport:output_type -> scg.v1.services.GenerateComplianceReportResponse
	3, // 7: scg.v1.services.ReportingService.GenerateMonthlyReport:output_type -> scg.v1.services.GenerateComplianceReportResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_services_reporting_proto_init() }
func file_v1_services_reporting_proto_init() {
	if File_v1_services_reporting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_services_reporting_proto_rawDesc), len(file_v1_services_reporting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_services_reporting_proto_goTypes,
		DependencyIndexes: file_v1_services_reporting_proto_depIdxs,
		MessageInfos:      file_v1_services_reporting_proto_msgTypes,
	}.Build()
	File_v1_services_reporting_proto = out.File
	file_v1_services_reporting_proto_goTypes = nil
	file_v1_services_reporting_proto_depIdxs = nil
}
